language: node_js
node_js:
  - "8.9.3"

cache:
  yarn: true
  directories:
  - node_modules
  - firebase/functions/node_modules

branches:
  only:
    - master

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
  - yarn global add firebase-tools
  - yarn global add replace-in-file
  - yarn

script:
  - yarn run lint
  - yarn run replace ApiKey $FIERBASE_AUTH_API_KEY src/environments/environment.prod.ts
  - yarn run test
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change