language: node_js
node_js:
  - "8.9.3"

cache:
  yarn: true
  directories:
  - node_modules
  - firebase/functions/node_modules

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - yarn

script:
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change